import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { TaskProvider } from '@/contexts/task'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={inter.className}>
      <body className="flex h-screen w-screen flex-col">
        <TaskProvider>
          <header className="flex h-52 w-screen bg-gray-700">
            <div className="mx-auto w-full max-w-screen-xl px-10">
              <h1 className="mt-14 text-5xl font-extrabold text-yellow-500">
                TasK
              </h1>
            </div>
          </header>
          <main className="h-screen w-screen bg-gray-600">
            <div className="mx-auto -mt-7 flex w-full max-w-screen-xl flex-col px-10">
              {children}
            </div>
          </main>
        </TaskProvider>
      </body>
    </html>
  )
}
